name: Makefile CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up OCaml
      run: |
        sudo apt install ocaml ocaml-findlib
    
    - name: build
      run: make dpll

  release:
    name: release the app
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: pack
      run: make pack
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        files: |
          *.zip
